### ISSUE TITLE
Add Margin Between Email and Address

### ISSUE THREAD

**Issue by lcarranco** [Carrancos/Autoresponder-CFA#1]
I want to have a bit of space between the email and address, but I do not want to use p tags because that will add too much spacing. I tried adding margin to the bottom of the address, as shown below, but it did not work. 

- `<a style="font-family: Arial, sans-serif; font-size: 14px; margin-bottom: 15px;" href="mailto:eric@crossfitachievehouston.com">eric@crossfitachievehouston.com</a>`

**Comment by carranj** [comment]
since this is an email, using tables is the best practice. I went pushed  a resolution on how to add some space between the email and address.

**Comment by lcarranco** [comment]
Thanks for your help!
